#!/bin/bash
clear
###################################################################################
# Source: https://github.com/tmlarsson/mktex
###################################################################################

# Initial setup
BIBER=False
CLEAN=False
MINTED= # -shell-escape only needs to be used when minted is used due to potentially security flaw.
compiler="pdflatex"

# Check for input
if [ "$#" == 0 ]; then
    echo "No input..."
    exit 1
fi

while [[ $# > 0 ]]
do
key="$1"
case $key in
    -b|--biber)
    BIBER=true
    ;;
    -c|--clean)
    CLEAN=true
    ;;
    -h|--help)
    HELP=true
    ;;
    -m|--minted)
    MINTED="-shell-escape"
    ;;
    -o|--open)
    OPEN=true
    ;;
    --tikz)
    TIKZ=true
    ;;
    -std=lua)
    compiler="lualatex"
    ;;
    --update)
    update=true
    ;;
    --gettex)
    gettex=true
    ;;
    *)
    TEMP="$1"
    if [[ $TEMP =~ ".tex" ]]; then
        TEMP=${TEMP%.tex}
    fi
    if [[ "$TEMP" =~ "." ]]; then
        TEMP=${TEMP%.}
    fi
    if [[ ${TEMP:0:1} == "-" ]]; then
        echo "ERROR: \"$TEMP\" is not a valid argument..."
        echo ""
        echo "Here is the help for you:"
        echo ""
        HELP=true
    elif [ ! -f "$TEMP.tex" ]; then
        echo "The file \"$TEMP\" does not exist..."
        exit 1  
    fi

    FILENAME="$TEMP"
    ;;
esac
shift # go to next argument or value
done


if [ "$HELP" == true ]; then
    echo "mktex - Compiles LaTeX documents with pdfLaTeX"
    echo " "
    echo "Usage example: [possible flags]"
    echo "mktex filename [-b -c -m]"
    echo " "
    echo "options:"
    echo "-h, --help            show brief help"
    echo "-b, --biber           compile using biber"
    echo "-c, --clean           remove unnecessary files"
    echo "-m, --minted          Use this flag to use minted"
    echo "--tikz                Compile only TikZ picures in standalone mode"
    echo "-std=lua              Changes the default compiler to lualatex"
    echo "--update              Updates mktex into the newest found on github"
    echo "--gettex              Fetches the latest latex-template from kwlg"
    exit 0
fi

# Updates mktex. This creates a script in the tmp folder
# that will fetch the newest file from github.
# This does however require the user to use the sudo 
# command to move the new file to the /usr/local/bin folder.
# However, since the program is open source you can always check
# the source code to inspect my work. This should always be done
# since you should NEVER run some random code of the internet 
# which requires the sudo command without trusting it. NEVER!
if [ ! -z $update ]; then
    # Checks if update is run as root. 
    # Otherwise it terminates the script
    if [[ $EUID -ne 0 ]]; then
        echo "Update must be run as root" 1>&2
        exit 1
    fi
    cd /tmp
    touch tmpupdate.sh
    echo "#!/bin/bash" > tmpupdate.sh
    echo "echo -n Fetching update from github..." >> tmpupdate.sh
    echo "if git clone https://github.com/tmlarsson/mktex &>/dev/null" >> tmpupdate.sh
    echo "then" >> tmpupdate.sh
    echo "echo [OK]" >> tmpupdate.sh
    echo "cd mktex && sudo mv mktex /usr/local/bin" >> tmpupdate.sh
    echo "cd ../ && rm -rf mktex" >> tmpupdate.sh
    echo "sudo chmod +x /usr/local/bin/mktex" >> tmpupdate.sh
    echo "else" >> tmpupdate.sh
    echo "echo && echo Failed to get update..." >> tmpupdate.sh
    echo "rm -rf mktex" >> tmpupdate.sh
    echo "fi" >> tmpupdate.sh
    chmod +x tmpupdate.sh
    ./tmpupdate.sh
    rm tmpupdate.sh
    exit 0
fi


# Fetches the latex template from kwlg on github.
if [ ! -z $gettex ]; then
    dir=$PWD
    echo -n "Fetching the template..."
    
    cd /tmp

    if [ -d "latex-template" ]; then
        mv latex-template latex-template-moved
    fi
    
    if git clone https://github.com/kwlg/latex-template &>/dev/null
    then
        echo "[OK]"
        cd latex-template
        mv *.tex $dir
        cd ..
        rm -rf latex-template
    else
        echo ""
        echo "Failed to get template..."
    fi
    exit 0
fi


# Check for existance of the compiler. If it does not exist,
# the script will exit.
type $compiler >/dev/null 2>&1 || { echo >&2 "I require $compiler but it's not installed. Aborting."; exit 1; }

# Check if no filename is specified.
# If no filename is given then exit the program
if [ -z $FILENAME ]; then
    echo "No filename was specified..."
    exit 0
fi

# If one only wants to compile a tikz picure
# That code is exectued below
# If in TikZ mode the regular code for compiling a 
# document will be skipped
if [ "$TIKZ" == true ]; then
    echo -n "Compiling TikZ picure using $compiler..."

    tikzresult=$(max_print_line=2048 $compiler $MINTED -interaction=nonstopmode -file-line-error "${FILENAME%.tex}" 2>/tmp/tikzERR | grep -i "^.*:[0-9]*:.*\|warning.*$")

    if [ -z "$tikzresult" ]; then
        echo "[OK]"
    else
        echo ""
        echo ""
        echo "Found some errors..."
        echo ""
        echo $tikzresult
        tikzERR=$(cat /tmp/tikzERR)
        if [ ! -z "$tikzERR" ]; then
            echo ""
            echo $tikzERR
            echo ""
        fi
    fi    
fi


# Compile document only if not in TIKZ mode
if [ -z "$TIKZ" ]; then

# Just adds some visual niceness
if [ "$BIBER" == true ]; then
    echo "Compile using $compiler and biber..."
else
    echo "Compile using $compiler..."
fi

# First sweep of the compilation. I have chosen to compile
# twice due to the fact that references takes two sweeps to
# fully update. Due to that fact, the output of the first
# sweep will be neglected since this usually contain errors
# not present in the second sweep.
echo -n "$compiler: First sweep..."
max_print_line=2048 $compiler $MINTED -interaction=nonstopmode -file-line-error "${FILENAME%.tex}" >/dev/null 2>&1
echo "[OK]"

# If one uses biber for references one also has to compile 
# with biber. One bug, at least on OS X happens sometimes
# where the chache has to be removed for the program to 
# compile. This take care of that automatically.
if [ "$BIBER" == true ]; then
    runAgain=true
    while [ "$runAgain" == true ]; do
        echo -n "biber..."
        bibRES=$(biber "$FILENAME" 2>/tmp/biber)
        bibERR=$(</tmp/biber)
        echo "[OK]"

        # Check fo data bug in biber
        vartest=$(echo "$bibERR" | grep "no data found")
        if [ ! -z "$vartest" ]; then
            rm -rf `biber --cache`
            echo ""
            echo "Removed biber cache..."
            echo "Compiling again..."
            runAgain=true
        else
            runAgain=false
        fi
    done
fi

# Second sweep with the given compiler
echo -n "$compiler: Second sweep..."

result=$(max_print_line=2048 $compiler $MINTED -interaction=nonstopmode -file-line-error "${FILENAME%.tex}" 2>/tmp/latexerr | grep -i "^.*:[0-9]*:.*\|warning.*$") 
echo "[OK]"

# Prints the result, if there is any errors to display.
if [ -z "$result" ]; then
    echo ""
    echo 'Compiled without errors!'
else
    echo ""
    echo "Compiled with warnings in $compiler..."
    echo""
    echo "$result"
    latexERR=$(cat /tmp/latexerr)
    #echo $latexERR

    if [ ! -z "$latexERR" ]; then
        echo ""
        cat /tmp/latexerr
        echo ""
    fi
fi


if [ $BIBER == true ]; then
if [ -z "$bibRES" ]; then
    echo ""
    echo 'Compiled without errors in biber!'
else
    echo ""
    echo "Compiled with errors in biber..."
    echo""
    echo "$bibRES"
    echo ""
    echo "$bibERR"
fi
fi
fi
# Remove unnessesary files.
if [ "$CLEAN" == true ]; then
    if [ -f "${FILENAME}.log" ]; then
        rm *.log
    fi
    if [ -f "${FILENAME}.lof" ]; then
        rm *.lof
    fi
    if [ -f "${FILENAME}.blg" ]; then
        rm *.blg
    fi
    if [ -f "${FILENAME}.toc" ]; then
        rm *.toc
    fi
    if [ -f "${FILENAME}.out" ]; then
        rm *.out
    fi

    if [ -f "${FILENAME}.bbl" ]; then
        rm *.bbl
    fi
    if [ -f "${FILENAME}.aux" ]; then
        rm *.aux
    fi
    if [ -f "${FILENAME}.bcf" ]; then
        rm *.bcf
    fi
    if [ -f "${FILENAME}.run.xml" ]; then
        rm *.run.xml
    fi
    if [ -f "${FILENAME}.tex.bak" ]; then
        rm *.tex.bak
    fi
    if [ -f "${FILENAME}.fls" ]; then
        rm *.fls
    fi
    if [ -f "${FILENAME}.fdb_latexmk" ]; then
        rm *.fdb_latexmk
    fi
fi

# Opens the file if the -o flag was specified
if [ "$OPEN" == true ]; then
    if [[ "$OSTYPE" == "linux-gnu" ]]; then
        xdg-open "${FILENAME}.pdf"
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        open "${FILENAME}.pdf"
    fi
fi
